[nexus]
priority = 10
sync-uri = https://github.com/Ackerman-00/gentoo-nexus/releases/download/rolling/
location = /var/cache/binhost/nexus
verify-signature = false

[gentoo-official-v3]
priority = 5
sync-uri = https://distfiles.gentoo.org/releases/amd64/binpackages/23.0/x86-64-v3/
location = /var/cache/binhost/gentoo-official-v3
verify-signature = true
